workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'

stages:
  - build
  - test
  - image_build
  - deploy_dev

variables:
  NODE_IMAGE: node:18-alpine
  IMAGE_NAME: mzm1/node-swagger-metrics
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_DRIVER: overlay2
  K8S_MANIFEST_PATH: node-app-k8s/node-app-k8s-manifest-dev


default:
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths: 
        - node-modules/

# -------------------
# Install dependencies
# -------------------
build:
  stage: build
  image: $NODE_IMAGE
  script:
    - echo "Installing dependencies..."
    - npm install --production
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: always


# -------------------
# Run tests
# -------------------
test:
  stage: test
  image: $NODE_IMAGE
  dependencies:
    - build
  script:
    - echo "Running tests..."
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: always



# -------------------
# Build Docker image
# -------------------
image_build:
  stage: image_build
  image: docker
  dependencies:
    - build
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
   - docker build -t $IMAGE_NAME:$IMAGE_TAG .
   - docker push $IMAGE_NAME:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: always


# -------------------
# Deploy
# -------------------
deploy-dev:
  stage: deploy_dev
  dependencies:
    - image_build
  image: bitnami/kubectl:latest
  tags:
    - k8s
    
  script:
    - git clone http://oauth2:$GITLAB_TOKEN@192.168.0.115/mohammed.zuhair/node-app-k8s
    - yq -i ".spec.template.spec.containers[0].image = \"$IMAGE_NAME:$IMAGE_TAG\"" $K8S_MANIFEST_PATH/node-app-deployment.yml
    - cd $K8S_MANIFEST_PATH
    - git add node-app-deployment.yml
    - git config --local user.name "GitLab CI"
    - git config --local user.email "ci@gitlab.com"
    - git commit -m "Update image to $IMAGE_TAG from $CI_COMMIT_REF_NAME"
    - git push origin main
    - cd ../..
    - kubectl apply -f $K8S_MANIFEST_PATH
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: always

