services:

  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - .env

    volumes:
      - ./secrets:/app/secrets:ro
