name: Node.js CD

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Image tag to deploy
        required: true
        type: string

jobs:

  # ============================================================
  # DEV
  # ============================================================
  Deploy-to-Dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest

    environment:
      name: dev

    concurrency:
      group: update-k8s-repo
      cancel-in-progress: false

    steps:
      - name: Clone Kubernetes manifest repository
        run: |
          git clone \
            https://x-access-token:${{ secrets.GH_PAT }}@github.com/mohammedzuhair25/node-js-example-k8s.git

      - name: Install yq
        uses: mikefarah/yq@v4.47.2

      - name: Update Dev manifest
        run: |
          cd node-js-example-k8s/k8s/helm-node-app

          yq -i \
            ".image.tag = \"${{ inputs.image_tag }}\"" \
            values-dev.yaml

          echo "Updated Dev manifest:"
          cat values-dev.yaml

      - name: Commit and push Dev
        run: |
          cd node-js-example-k8s

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add k8s/helm-node-app/values-dev.yaml

          git diff --cached

          git commit \
            -m "Update dev image to ${{ inputs.image_tag }}" \
            || echo "No changes to commit"

          git push origin main


  # ============================================================
  # STAGING
  # ============================================================
  Deploy-to-Staging:
    name: Deploy to Staging

    needs:
      - Deploy-to-Dev

    runs-on: ubuntu-latest

    environment:
      name: staging

    concurrency:
      group: update-k8s-repo
      cancel-in-progress: false

    steps:
      - name: Clone Kubernetes manifest repository
        run: |
          git clone \
            https://x-access-token:${{ secrets.GH_PAT }}@github.com/mohammedzuhair25/node-js-example-k8s.git

      - name: Install yq
        uses: mikefarah/yq@v4.47.2

      - name: Update Staging manifest
        run: |
          cd node-js-example-k8s/k8s/helm-node-app

          yq -i \
            ".image.tag = \"${{ inputs.image_tag }}\"" \
            values-staging.yaml

          echo "Updated Staging manifest:"
          cat values-staging.yaml

      - name: Commit and push Staging
        run: |
          cd node-js-example-k8s

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add k8s/helm-node-app/values-staging.yaml

          git diff --cached

          git commit \
            -m "Update staging image to ${{ inputs.image_tag }}" \
            || echo "No changes to commit"

          git push origin main
