name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - hotfix/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: mohammedzuhair25/node-js-project-example/.github/workflows/node.js.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
   

  deploy-dev:
    needs: ci
    uses: mohammedzuhair25/node-js-project-example/.github/workflows/Dev-CD.yml@main
    with:
      environment: dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}