name: CI

on:
  push:
    branches:
      - feature/**
      - develop/**
      - hotfix/**
  workflow_dispatch:

jobs:
  call-ci:
    uses: mohammedzuhair25/node-js-project-example/.github/workflows/node.js.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}

  deploy:
    needs: call-ci
    uses: mohammedzuhair25/node-js-project-example/.github/workflows/Dev-CD.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
    if: github.ref == 'refs/heads/main'